// Research presentation for the smi project.
//
// Build:  pixi run report-slides   (or, from report/: snakemake build/slides.pdf)
// Figures are generated by report/figures/plot_*.py into build/figures/ and
// are inputs to this document -- do not hand-edit anything under build/.
//
// One `=` heading is one slide. Keep each slide to a single page: after
// editing, render and check the page count did not grow, since Typst will
// happily continue an overlong slide onto a second page without complaining.
//
// ASCII only, per the repo convention. Write "um", "->", "<=" rather than the
// Unicode glyphs.

#import "lib/theme.typ": fig, slides-theme, takeaway

#show: slides-theme.with(
  title: "Self-mixing interferometry for rapid vibration spectrograms",
  subtitle: "Learning velocity directly from multi-wavelength photodiode traces",
  author: "Nolan Peard",
  date: "Status update",
)

= The problem

A Michelson interferometer encodes displacement as a phase, and the detector
only sees its cosine:

$ s(t) = cos( (4 pi) / lambda d(t) + phi.alt ) $

- *Fringe ambiguity.* One channel cannot tell $d$ from $d + lambda\/2$, and it
  loses direction whenever the velocity crosses zero.
- *Drift.* Amplitude, DC level and the offset $phi.alt$ wander between shots,
  so a fixed inverse does not transfer.

#takeaway[
  Target: *velocity* $dot(d)(t)$ at full rate, from the raw photodiode traces
  alone. Three wavelengths (635, 675, 515 nm) break the ambiguity in
  principle; the question is what does the unwrapping.
]

= Acquisition and what the data looks like

#fig(
  "pd_traces",
  width: 61%,
  caption: [
    One real shot, 16384 samples at 488.28 kHz. (a) speaker drive voltage;
    (b)-(d) the three photodiode channels. Fringe rate tracks $|dot(d)|$, and
    the channels lose and regain contrast independently.
  ],
)

= Ground truth comes from the drive, not a reference interferometer

// Width is load-bearing, not cosmetic: this figure is three stacked panels,
// so it is tall for its width. At 58% it pushed the caption onto a second
// page. `pixi run report` fails on that now (check_slide_pages.py), but the
// fix if it recurs is to shrink the figure, not to raise the page budget.
#fig(
  "drive_to_velocity",
  width: 46%,
  caption: [
    (a) Coil-driver gain: a damped resonator near 259 Hz with $Q approx 17$.
    (b) a real drive waveform and the displacement it implies. (c) the
    velocity target, from the displacement spectrum times $j 2 pi f$.
  ],
)

= Derived targets, and what that costs

#takeaway[
  Targets are *derived* from the drive voltage through a calibrated transfer
  function, not measured independently. Everything downstream inherits that
  calibration's accuracy.
]

That is the case for a *forward-model residual* baseline: fit the Michelson
model to the data using the known displacement, and see how much residual is
left. If the model cannot explain the data even when handed the right answer,
no inverse -- learned or not -- will do better.

= Free space versus multimode fiber

#fig(
  "freespace_vs_fiber",
  width: 70%,
  caption: [
    635 nm channel, same speaker and waveform family. (a) one shot from each
    acquisition. (b) mean amplitude spectrum, N = 64 shots. Mode scrambling in
    the fiber low-passes the fringe signal before the detector sees it.
  ],
)

= Data pipeline: does the dataset fit on the GPU?

#fig(
  "working_set",
  width: 66%,
  caption: [
    Measured from the real dataset shapes. The file looks small on disk only
    because it is gzip-compressed; inputs plus both targets come to 3.05 GiB
    resident -- fine on the 3090 Ti, not alongside a model on the 8 GiB Quadro.
  ],
)

= Throughput: where the time actually goes

Three regimes the loading benchmark has to separate: disk-bound, CPU-bound on
the per-sample FFT physics, or already hidden behind the GPU. Every
configuration runs a real forward and backward pass.

#takeaway[
  *It is GPU bound.* Every configuration with `num_workers >= 4` lands within
  3% of the model-only ceiling of about 212 samples/s, while the loader on
  its own supplies about 1573-1600 samples/s -- roughly 7.5-9x more than the
  model can consume.
]

- *Full GPU residency buys 1.7%*, which is inside the run-to-run noise. It is
  implemented as an opt-in mode, not a default, because the measurement does
  not justify one.
- The duplicate-FFT fix matters only at `num_workers = 0`, where the loader is
  on the critical path. With workers, it is hidden.

#text(size: 11pt, fill: rgb("#6a6a6a"))[
  Caveat: the 3090 Ti is also the display GPU, so absolute samples/s shifts
  between sessions. Only within-run ratios are meaningful.
]

= Baselines: what a non-learned method achieves

Before an accuracy claim about the network means anything, it needs a number
beside it from a method that does not learn.

- *Forward-model residual.* Known displacement, closed-form fit of per-shot
  amplitude and phase. Measures whether the model explains the data at all.
- *Multi-wavelength inverse.* From the photodiode signals alone: unwrap phase
  across three wavelengths, then differentiate. This is the number that goes
  next to the network's RMSE.

Scoring a shot by its likelihood and fitting it and reporting MSE are the same
computation: under Gaussian residuals the negative log-likelihood *is* the
summed squared residual, up to an additive constant and a positive scale. So
fit in closed form, report MSE, and the likelihood reading comes free.

= Results: the baseline, and what it exposes

// 78% orphaned the takeaway onto a second page. Three panels side by side
// stay legible well below that, so shrinking the figure is the fix rather
// than dropping the takeaway, which is the point of the slide.
#fig(
  "baseline_summary",
  width: 62%,
  caption: [
    Medians over N = 200 shots per acquisition, interquartile range as
    whiskers.
  ],
)

#takeaway[
  The inverse reaches 0.433 / 0.462 um displacement RMSE (488 / 550 um/s
  velocity) -- but NRMSE 1.10 / 1.18, i.e. just *worse than predicting zero*.
]

= Why the baseline is bad, and what that means

The forward-model residual says the problem is not the inverse. With
displacement *known*, the Michelson model still explains only 9-38% of the
variance, and the residual is 0.79-0.95x the signal RMS in every channel.

#fig(
  "baseline_amplitude_trend",
  width: 62%,
  caption: [
    Method-1 median $R^2$ by drive peak-to-peak excursion. Every channel in
    both acquisitions collapses to $R^2 <= 0.11$ above 2 um.
  ],
)

= What is settled and what is not

*Settled.*
- Acquisition and the supervision path work end to end on real hardware.
- Resident working set is 3.05 GiB per acquisition, so GPU residency is an
  option rather than a wish.
- Data loading was never the bottleneck. Training is GPU bound; the loader has
  7.5-9x headroom.
- The baseline: 488 / 550 um/s velocity RMSE, N = 200 per acquisition.
- The Michelson model does not explain this data, even given the true
  displacement. That is now the limiting problem.

*Open.*
- Why the forward model fails, and why it fails worse with excursion. The
  drive-to-displacement calibration is the first suspect, untested.
- Whether the network earns its complexity against a floor this low.
- The fiber gap is invisible in the baseline, so it remains unmeasured rather
  than absent.
