"""Known-answer tests for the non-deep-learning baselines.

Both baselines are exercised on synthetic data generated by the same
Michelson forward model the estimators assume, so the correct answer is known
exactly and a failure means the estimator is wrong -- not that the hardware
is noisy.
"""

import numpy as np
import pytest
import torch

from smi.analysis.baseline_fit import (
    PD_WAVELENGTHS_UM,
    fit_phase_amplitude,
    forward_model_residual,
    inverse_fit,
)
from smi.synthetic.interferometers import MichelsonInterferometer

SAMPLE_RATE = 488281.25

# The Viterbi decode is a long sequential loop over time samples. On a GPU it
# is a few hundred milliseconds; on CPU it is tens of seconds. Use the GPU
# when the machine has one so these known-answer checks stay cheap enough to
# live in the unit suite, and shrink the problem on CPU-only machines (CI).
DEVICE = 'cuda:0' if torch.cuda.is_available() else 'cpu'
DECODE_SAMPLES = 2048 if torch.cuda.is_available() else 768
GRID_POINTS = 1601 if torch.cuda.is_available() else 801
ENSEMBLE_SHOTS = 12 if torch.cuda.is_available() else 4


def _band_limited_displacement(
    n_samples: int, seed: int, amplitude_um: float = 0.35
) -> np.ndarray:
    """Smooth multi-tone displacement in the band the speaker actually drives.

    Returns:
        Zero-mean displacement in microns, shape ``(n_samples,)``.
    """
    rng = np.random.default_rng(seed)
    t = np.arange(n_samples) / SAMPLE_RATE
    disp = np.zeros(n_samples)
    for freq, weight in ((120.0, 1.0), (310.0, 0.6), (700.0, 0.3)):
        disp += weight * np.sin(2 * np.pi * freq * t + rng.uniform(0, 2 * np.pi))
    disp -= disp.mean()
    return disp * (amplitude_um / disp.std())


def _best_sign_rmse(estimate: np.ndarray, truth: np.ndarray) -> float:
    """RMSE under the better of the two sign conventions.

    ``cos`` is even, so the interferometer signals are identical for ``d(t)``
    and ``-d(t)``: the overall sign is genuinely unobservable from the
    fringes and must not be scored as an error.
    """
    return min(
        float(np.sqrt(np.mean((estimate - truth) ** 2))),
        float(np.sqrt(np.mean((-estimate - truth) ** 2))),
    )


def _synthesize(displacement: np.ndarray, phases, amplitudes) -> np.ndarray:
    """Build three-channel PD signals with the project's Michelson model."""
    channels = []
    for wavelength, phase, amp in zip(
        PD_WAVELENGTHS_UM.values(), phases, amplitudes, strict=True
    ):
        interferometer = MichelsonInterferometer(wavelength=wavelength, phase=phase)
        signal = amp * interferometer.get_interferometer_output(displacement)
        channels.append(signal - signal.mean())
    return np.stack(channels)


class TestClosedFormPhaseAmplitudeFit:
    """The method-1 fit must recover analytically known phase and amplitude."""

    @pytest.mark.parametrize('true_phase', [-2.5, -0.7, 0.0, 0.4, 1.9, 3.0])
    def test_recovers_known_phase_and_amplitude(self, true_phase: float) -> None:
        theta = np.linspace(0, 40 * np.pi, 4096)
        true_amplitude = 0.37
        signal = true_amplitude * np.cos(theta + true_phase)

        fit = fit_phase_amplitude(signal, theta)

        assert fit.amplitude == pytest.approx(true_amplitude, rel=1e-9)
        # Compare on the circle so the (-pi, pi] wrap is not a false failure.
        wrapped = np.angle(np.exp(1j * (fit.phase - true_phase)))
        assert wrapped == pytest.approx(0.0, abs=1e-9)
        assert fit.rmse == pytest.approx(0.0, abs=1e-9)
        assert fit.r_squared == pytest.approx(1.0, abs=1e-9)

    def test_recovers_constant_offset(self) -> None:
        theta = np.linspace(0, 30 * np.pi, 2048)
        signal = 0.2 * np.cos(theta - 1.1) + 0.05

        fit = fit_phase_amplitude(signal, theta)

        assert fit.offset == pytest.approx(0.05, abs=1e-9)
        assert fit.amplitude == pytest.approx(0.2, rel=1e-9)

    def test_noise_shows_up_as_residual_rmse(self) -> None:
        rng = np.random.default_rng(7)
        theta = np.linspace(0, 60 * np.pi, 8192)
        noise_sigma = 0.02
        signal = 0.3 * np.cos(theta + 0.8) + rng.normal(0, noise_sigma, theta.size)

        fit = fit_phase_amplitude(signal, theta)

        # With three free parameters out of 8192 samples, the residual RMSE is
        # the injected noise level to within sampling error.
        assert fit.rmse == pytest.approx(noise_sigma, rel=0.05)
        assert fit.amplitude == pytest.approx(0.3, rel=0.02)

    def test_rejects_mismatched_shapes(self) -> None:
        with pytest.raises(ValueError, match='matching shape'):
            fit_phase_amplitude(np.zeros(10), np.zeros(11))


class TestForwardModelResidual:
    """Method 1 against a signal the Michelson model generates exactly."""

    def test_exact_model_gives_zero_residual(self) -> None:
        disp = _band_limited_displacement(4096, seed=3)
        wavelength = 0.635
        interferometer = MichelsonInterferometer(wavelength=wavelength, phase=1.234)
        signal = 0.11 * interferometer.get_interferometer_output(disp)

        fit = forward_model_residual(signal, disp, wavelength)

        assert fit.r_squared == pytest.approx(1.0, abs=1e-10)
        assert fit.rmse < 1e-12
        assert fit.amplitude == pytest.approx(0.11, rel=1e-8)
        wrapped = np.angle(np.exp(1j * (fit.phase - 1.234)))
        assert wrapped == pytest.approx(0.0, abs=1e-8)

    def test_wrong_displacement_gives_large_residual(self) -> None:
        """A mis-scaled displacement must not fit -- otherwise the metric is
        blind to exactly the calibration error it exists to detect.
        """
        disp = _band_limited_displacement(4096, seed=5)
        wavelength = 0.635
        interferometer = MichelsonInterferometer(wavelength=wavelength, phase=0.0)
        signal = interferometer.get_interferometer_output(disp)

        good = forward_model_residual(signal, disp, wavelength)
        bad = forward_model_residual(signal, disp * 1.3, wavelength)

        assert good.r_squared > 0.999
        assert bad.r_squared < 0.5


class TestInverseFit:
    """Method 2 must recover a known displacement from PD signals alone."""

    def test_recovers_known_displacement(self) -> None:
        """A clean single shot with generic phases must decode almost exactly.

        Tolerance is set against the physics, not against the observed
        output: 0.02 um is under a tenth of the shortest half-wavelength
        fringe (0.515/2 = 0.2575 um), so passing means the decoder resolved
        the correct fringe order rather than landing on a neighbour.
        """
        disp = _band_limited_displacement(DECODE_SAMPLES, seed=11, amplitude_um=0.30)
        signals = _synthesize(disp, phases=(0.3, -1.1, 2.2), amplitudes=(1.0, 0.8, 1.2))

        result = inverse_fit(
            signals,
            sample_rate=SAMPLE_RATE,
            wavelengths_um=list(PD_WAVELENGTHS_UM.values()),
            displacement_limit_um=1.5,
            grid_points=GRID_POINTS,
            max_speed_um_per_s=4000.0,
            device=DEVICE,
        )

        assert _best_sign_rmse(result.displacement[0], disp) < 0.02

    def test_recovers_displacement_across_random_phases(self) -> None:
        """The decoder must work for arbitrary interferometer phase offsets.

        Real interferometers sit at an uncontrolled phase, so a single
        hand-picked phase triple would not show whether the estimator is
        generally reliable. Scored over an ensemble: the typical shot must
        decode tightly and the large majority must decode at all.
        """
        n_shots = ENSEMBLE_SHOTS
        rng = np.random.default_rng(99)
        shots = [
            _band_limited_displacement(DECODE_SAMPLES, seed=200 + i, amplitude_um=0.30)
            for i in range(n_shots)
        ]
        batch = np.stack(
            [
                _synthesize(d, rng.uniform(0, 2 * np.pi, 3), (1.0, 1.0, 1.0))
                for d in shots
            ]
        )

        result = inverse_fit(
            batch,
            sample_rate=SAMPLE_RATE,
            wavelengths_um=list(PD_WAVELENGTHS_UM.values()),
            displacement_limit_um=1.5,
            grid_points=GRID_POINTS,
            max_speed_um_per_s=4000.0,
            device=DEVICE,
        )

        nrmse = np.array(
            [
                _best_sign_rmse(result.displacement[i], shots[i]) / shots[i].std()
                for i in range(n_shots)
            ]
        )
        assert np.median(nrmse) < 0.06
        assert (nrmse < 0.10).mean() >= 0.75

    def test_recovers_velocity(self) -> None:
        """Velocity must follow from the decode, not just displacement.

        The decoded displacement is grid-quantized, so this is really a check
        that the derivative is taken in a way that does not amplify the
        quantization step into nonsense.
        """
        disp = _band_limited_displacement(DECODE_SAMPLES, seed=17, amplitude_um=0.30)
        true_velocity = np.gradient(disp, 1.0 / SAMPLE_RATE)
        signals = _synthesize(disp, phases=(1.0, 2.0, 3.0), amplitudes=(1.0, 1.0, 1.0))

        result = inverse_fit(
            signals,
            sample_rate=SAMPLE_RATE,
            wavelengths_um=list(PD_WAVELENGTHS_UM.values()),
            displacement_limit_um=1.5,
            grid_points=GRID_POINTS,
            max_speed_um_per_s=4000.0,
            device=DEVICE,
        )

        nrmse = _best_sign_rmse(result.velocity[0], true_velocity) / true_velocity.std()
        assert nrmse < 0.30

    def test_velocity_derivative_beats_naive_difference(self) -> None:
        """The smoothed derivative must actually help, not just exist."""
        disp = _band_limited_displacement(DECODE_SAMPLES, seed=17, amplitude_um=0.30)
        true_velocity = np.gradient(disp, 1.0 / SAMPLE_RATE)
        signals = _synthesize(disp, phases=(1.0, 2.0, 3.0), amplitudes=(1.0, 1.0, 1.0))

        result = inverse_fit(
            signals,
            sample_rate=SAMPLE_RATE,
            wavelengths_um=list(PD_WAVELENGTHS_UM.values()),
            displacement_limit_um=1.5,
            grid_points=GRID_POINTS,
            max_speed_um_per_s=4000.0,
            device=DEVICE,
        )
        naive = np.gradient(result.displacement[0], 1.0 / SAMPLE_RATE)

        smoothed_err = _best_sign_rmse(result.velocity[0], true_velocity)
        naive_err = _best_sign_rmse(naive, true_velocity)
        assert smoothed_err < 0.5 * naive_err

    def test_batched_shots_match_single_shot(self) -> None:
        """Batching is an efficiency detail; it must not change the answer."""
        shots = [
            _band_limited_displacement(1024, seed=s, amplitude_um=0.25)
            for s in (21, 22)
        ]
        batch = np.stack(
            [_synthesize(d, (0.4, -0.6, 1.7), (1.0, 0.9, 1.1)) for d in shots]
        )

        kwargs = {
            'sample_rate': SAMPLE_RATE,
            'wavelengths_um': list(PD_WAVELENGTHS_UM.values()),
            'displacement_limit_um': 1.2,
            'grid_points': 601,
            'max_speed_um_per_s': 4000.0,
            'phase_grid_points': 8,
            'phase_search_samples': 384,
            'device': DEVICE,
        }
        batched = inverse_fit(batch, **kwargs)
        for j in range(2):
            single = inverse_fit(batch[j], **kwargs)
            np.testing.assert_allclose(
                single.displacement[0], batched.displacement[j], atol=1e-9
            )

    def test_rejects_channel_count_mismatch(self) -> None:
        with pytest.raises(ValueError, match='wavelengths'):
            inverse_fit(
                np.zeros((3, 256)),
                sample_rate=SAMPLE_RATE,
                wavelengths_um=[0.635, 0.675],
                displacement_limit_um=1.0,
                grid_points=101,
            )
